apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "password-generator.fullname" . }}-claim
  labels:
    app: {{ include "password-generator.fullname" . }}-pv
spec:
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
  {{- end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
