apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "password-generator.fullname" . }}
spec:
  gateways:
  - {{ .Values.istio.gateway }}
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /{{ .Values.env.app_path }}
    route:
    - destination:
        host: {{ include "password-generator.fullname" . }}
        port:
          number: 8080
      headers:
        response:
          add:
            Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
