FROM ubuntu:20.04


# docker buildx build --platform linux/arm64,linux/amd64 -t david62243/ubuntu:20.04 . -f Dockerfile --push

RUN apt-get update \
    && apt-get install -y curl telnet iputils-ping 
