FROM ubuntu:20.04

# docker build -t david62243/django:ubuntu . -f Dockerfile.django:ubuntu
# docker push david62243/django:ubuntu

RUN apt update && \
    apt install -y curl python3 python3-pip postgresql 

RUN pip3 install virtualenv

WORKDIR /root
