FROM david62243/django:v1.0

# docker build -t david62243/password-generator:v1.0 -f Dockerfile.password-generator .
# docker push david62243/password-generator:v1.0

RUN adduser -Du 1000 duser 

RUN mkdir /home/duser/django

ADD password_generator_application.tgz /home/duser

RUN chown -R 1000:1000 /home/duser 

RUN ln -s /usr/bin/python3 /usr/local/bin/python

USER duser
WORKDIR /home/duser
